tankS3FileCreatedHandler:
  handler: tankS3FileCreatedHandler.process
  timeout: 900
  tags:
    DEPARTMENT: MACHINERY
    ENVIRONMENT: DEV

  events:
    - existingS3:
        bucket: ${self:custom.commandeer-tanks}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .json
